language: java
jdk: oraclejdk8
if: tag IS blank
before_install:
 - git clone --depth=50 --branch=master https://github.com/WIP-name/Painting-Mod.git .
 - git clone --depth=50 --branch=pre-release https://github.com/WIP-name/Painting-Mod.git .
install: 
 - ./gradlew setupCiWorkspace
script: 
 - ./gradlew build
 - |
    if [ "$TRAVIS_BRANCH" == "pre-release" ]; then
      ./gradlew makeChangelog --stacktrace
      ./gradlew githubRelease
    fi

# deploy:
# - provider: releases
#   api_key: $GH_TOKEN
#   file_glob: true
#   file: build/libs/*
#   skip_cleanup: true
#   prerelease: true
#   on:
#     tags: true
#     branch: pre-release
  
# - provider: releases
#   api_key: $GH_TOKEN
#   file_glob: true
#   file: build/libs/*
#   skip_cleanup: true
#   prerelease: false
#   on:
#     tags: true
#     branch: release
