language: java
jdk: oraclejdk8
before_install:
 - wget https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.4.2705/forge-1.12.2-14.23.4.2705-mdk.zip
 - unzip -n forge-1.12.2-14.23.4.2705-mdk.zip
 - rm forge-1.12.2-14.23.4.2705-mdk.zip
install: ./gradlew setupCiWorkspace
script: ./gradlew build

before_deploy:
  - git config --local user.name "arthurbambou"
  - git config --local user.email "arthur.koalas@free.fr"
  - git tag $(TRAVIS_COMMIT)
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: build/libs/*
  #name: $TRAVIS_COMMIT
  #body: `${TRAVIS_COMMIT_MESSAGE} \n Commit List \n ${TRAVIS_COMMIT_RANGE}`
  skip_cleanup: true
  prerelease: true
  on:
    branch: pre-release
  
  provider: releases
  #name: $TRAVIS_COMMIT
  #body: `${TRAVIS_COMMIT_MESSAGE} \n Commit List \n ${TRAVIS_COMMIT_RANGE}`
  api_key: $GH_TOKEN
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  prerelease: false
  on:
    branch: release